name: Test_Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App Name'
        required: true
        default: ''
      buster_32:
        description: 'Build on PiOS Buster 32bit'
        required: true
        type: boolean
      bullseye_32:
        description: 'Build on PiOS Bullseye 32bit'
        required: true
        type: boolean
      buster_64:
        description: 'Build on PiOS Buster 64bit'
        required: true
        type: boolean
      bullseye_64:
        description: 'Build on PiOS Bullseye 64bit'
        required: true
        type: boolean
      bionic_64:
        description: 'Build on Nvidia Jetpack 32.3.1 Bionic 64bit'
        required: true
        type: boolean
      focal_64:
        description: 'Build on Nvidia Jetpack 35.1.0 Focal 64bit'
        required: true
        type: boolean
      jammy_64:
        description: 'Build on RPI Ubuntu Jammy 64bit'
        required: true
        type: boolean

run-name: Testing ${{ inputs.app_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buster-32bit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ inputs.buster_32 }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Test installing app on buster armhf
        uses: theofficialgman/arm-runner-action@v4
        with:
          # this is a buster armhf image
          base_image: https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-09-26/2022-09-22-raspios-buster-armhf.img.xz
          # bind mount the directory so any changes propogate to outside the chroot
          bind_mount_repository: yes

          # give the image more space
          image_additional_mb: 5000

          # set CPUs to use
          cpu: cortex-a7:cortex-a72

          # user runner name as default path
          copy_repository_path: /home/runner/pi-apps

          # export github env back to outside the chroot
          export_github_env: yes

          import_github_env: true

          # set shell to bash
          shell: /bin/bash
          commands: |
            export app_name="${{ inputs.app_name }}"
            ./.github/workflows/test_build_commands.sh

  bullseye-32bit:
    runs-on: ubuntu-latest
    if: ${{ inputs.bullseye_32 }}
    steps:
      - uses: actions/checkout@v3
      - name: Test installing app on bullseye armhf
        uses: theofficialgman/arm-runner-action@v4
        with:
          base_image: https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2022-09-26/2022-09-22-raspios-bullseye-armhf.img.xz
          bind_mount_repository: yes
          image_additional_mb: 5000
          cpu: cortex-a7:cortex-a72
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export app_name="${{ inputs.app_name }}"
            ./.github/workflows/test_build_commands.sh

  buster-64bit:
    runs-on: ubuntu-latest
    if: ${{ inputs.buster_64 }}
    steps:
      - uses: actions/checkout@v3
      - name: Test installing app on buster arm64
        uses: theofficialgman/arm-runner-action@v4
        with:
          base_image: https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/2021-05-07-raspios-buster-arm64.zip
          bind_mount_repository: yes
          image_additional_mb: 5000
          cpu: cortex-a7:cortex-a72
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export app_name="${{ inputs.app_name }}"
            ./.github/workflows/test_build_commands.sh

  bullseye-64bit:
    runs-on: ubuntu-latest
    if: ${{ inputs.bullseye_64 }}
    steps:
      - uses: actions/checkout@v3
      - name: Test installing app on bullseye arm64
        uses: theofficialgman/arm-runner-action@v4
        with:
          base_image: https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-09-26/2022-09-22-raspios-bullseye-arm64.img.xz
          bind_mount_repository: yes
          image_additional_mb: 5000
          cpu: cortex-a7:cortex-a72
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export app_name="${{ inputs.app_name }}"
            ./.github/workflows/test_build_commands.sh

  bionic-64bit:
    runs-on: ubuntu-latest
    if: ${{ inputs.bionic_64 }}
    steps:
      - uses: actions/checkout@v3
      - name: Test installing app on bionic arm64
        uses: theofficialgman/arm-runner-action@v4
        with:
          base_image: https://developer.download.nvidia.com/embedded/L4T/r32-3-1_Release_v1.0/Jetson-Nano-SDCard-Image/nv-jetson-nano-sd-card-image-r32.3.1.zip
          # add special arguments for jetson nano image format
          bootpartition:
          rootpartition: 1
          bind_mount_repository: yes
          image_additional_mb: 5000
          # use TX1 ARM CPU cores
          cpu: cortex-a57
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export app_name="${{ inputs.app_name }}"
            ./.github/workflows/test_build_commands.sh

  focal-64bit:
    runs-on: ubuntu-latest
    if: ${{ inputs.focal_64 }}
    steps:
      - uses: actions/checkout@v3
      - name: Test installing app on focal arm64
        uses: theofficialgman/arm-runner-action@v4
        with:
          base_image: https://developer.download.nvidia.com/embedded/L4T/r35_Release_v1.0/JP_SD_5.0.2_b231/Jetson_SD_Xavier_NX/JP502-xnx-sd-card-image-b231.zip
          bootpartition:
          rootpartition: 1
          bind_mount_repository: yes
          image_additional_mb: 5000
          cpu: cortex-a72
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export app_name="${{ inputs.app_name }}"
            ./.github/workflows/test_build_commands.sh

  jammy-64bit:
    runs-on: ubuntu-latest
    if: ${{ inputs.jammy_64 }}
    steps:
      - uses: actions/checkout@v3
      - name: Test installing app on jammy arm64
        uses: theofficialgman/arm-runner-action@v4
        with:
          base_image: https://cdimage.ubuntu.com/releases/22.04.1/release/ubuntu-22.04.1-preinstalled-desktop-arm64+raspi.img.xz
          bind_mount_repository: yes
          image_additional_mb: 5000
          cpu: cortex-a7:cortex-a72
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export app_name="${{ inputs.app_name }}"
            ./.github/workflows/test_build_commands.sh